export const transportations = [
  {
    id: 1,
    customer: 'Customer 1',
    carrier: 'Carrier 1',
    startLocation: 'Київ',
    endLocation: 'Харків',
    cargoWeight: 1000,
    maxWeight: 2000,
    carBrand: 'Brand 1',
    startDate: '2023-06-01',
    endDate: '2023-06-05',
    routeCities: ['Біла Церква', 'Полтава'],
    distance: 471,
  },
  {
    id: 2,
    customer: 'Customer 2',
    carrier: 'Carrier 2',
    startLocation: 'Львів',
    endLocation: 'Одеса',
    cargoWeight: 1500,
    maxWeight: 2500,
    carBrand: 'Brand 2',
    startDate: '2023-06-02',
    endDate: '2023-06-06',
    routeCities: ['Тернопіль', 'Вінниця', 'Миколаїв'],
    distance: 700,
  },
  {
    id: 3,
    customer: 'Customer 3',
    carrier: 'Carrier 3',
    startLocation: 'Харків',
    endLocation: 'Дніпро',
    cargoWeight: 2000,
    maxWeight: 3000,
    carBrand: 'Brand 3',
    startDate: '2023-06-03',
    endDate: '2023-06-07',
    routeCities: ['Полтава', 'Запоріжжя'],
    distance: 337,
  },
  {
    id: 4,
    customer: 'Customer 4',
    carrier: 'Carrier 4',
    startLocation: 'Дніпро',
    endLocation: 'Київ',
    cargoWeight: 1200,
    maxWeight: 2200,
    carBrand: 'Brand 4',
    startDate: '2023-06-04',
    endDate: '2023-06-08',
    routeCities: ['Запоріжжя', 'Кропивницький', 'Черкаси'],
    distance: 379,
  },
  {
    id: 5,
    customer: 'Customer 5',
    carrier: 'Carrier 5',
    startLocation: 'Одеса',
    endLocation: 'Львів',
    cargoWeight: 1800,
    maxWeight: 2800,
    carBrand: 'Brand 5',
    startDate: '2023-06-05',
    endDate: '2023-06-09',
    routeCities: ['Миколаїв', 'Вінниця', 'Тернопіль'],
    distance: 773,
  },
  {
    id: 6,
    customer: 'Customer 6',
    carrier: 'Carrier 6',
    startLocation: 'Запоріжжя',
    endLocation: 'Дніпро',
    cargoWeight: 1500,
    maxWeight: 2500,
    carBrand: 'Brand 6',
    startDate: '2023-06-06',
    endDate: '2023-06-10',
    routeCities: ['Кропивницький', 'Полтава'],
    distance: 234,
  },
  {
    id: 7,
    customer: 'Customer 7',
    carrier: 'Carrier 7',
    startLocation: 'Черкаси',
    endLocation: 'Одеса',
    cargoWeight: 1600,
    maxWeight: 2600,
    carBrand: 'Brand 7',
    startDate: '2023-06-07',
    endDate: '2023-06-11',
    routeCities: ['Київ', 'Вінниця', 'Миколаїв'],
    distance: 538,
  },
  {
    id: 8,
    customer: 'Customer 8',
    carrier: 'Carrier 8',
    startLocation: 'Тернопіль',
    endLocation: 'Київ',
    cargoWeight: 1400,
    maxWeight: 2400,
    carBrand: 'Brand 8',
    startDate: '2023-06-08',
    endDate: '2023-06-12',
    routeCities: ['Львів', 'Вінниця', 'Черкаси'],
    distance: 444,
  },
  {
    id: 9,
    customer: 'Customer 9',
    carrier: 'Carrier 9',
    startLocation: 'Миколаїв',
    endLocation: 'Харків',
    cargoWeight: 1900,
    maxWeight: 2900,
    carBrand: 'Brand 9',
    startDate: '2023-06-09',
    endDate: '2023-06-13',
    routeCities: ['Одеса', 'Полтава'],
    distance: 581,
  },
  {
    id: 10,
    customer: 'Customer 10',
    carrier: 'Carrier 10',
    startLocation: 'Вінниця',
    endLocation: 'Запоріжжя',
    cargoWeight: 1300,
    maxWeight: 2300,
    carBrand: 'Brand 10',
    startDate: '2023-06-10',
    endDate: '2023-06-14',
    routeCities: ['Київ', 'Кропивницький'],
    distance: 486,
  },
];
