export const transportations = [
  {
    id: 1,
    customer: 'ТОВ "Експрес-Логістика"',
    carrier: 'ТОВ "АвтоТранс"',
    startLocation: 'Київ',
    endLocation: 'Харків',
    cargoWeight: 1000,
    maxWeight: 2000,
    carBrand: 'Mercedes-Benz',
    startDate: '2023-06-01',
    endDate: '2023-06-05',
    routeCities: ['Біла Церква', 'Полтава'],
    distance: 471,
  },
  {
    id: 2,
    customer: 'ПП "Торговий Дім"',
    carrier: 'ТОВ "Українська Транспортна Компанія"',
    startLocation: 'Львів',
    endLocation: 'Одеса',
    cargoWeight: 1500,
    maxWeight: 2500,
    carBrand: 'Volvo',
    startDate: '2023-06-02',
    endDate: '2023-06-06',
    routeCities: ['Тернопіль', 'Вінниця', 'Миколаїв'],
    distance: 700,
  },
  {
    id: 3,
    customer: 'ФОП Іваненко О.М.',
    carrier: 'ТОВ "Експрес Лайн"',
    startLocation: 'Харків',
    endLocation: 'Дніпро',
    cargoWeight: 2000,
    maxWeight: 3000,
    carBrand: 'Scania',
    startDate: '2023-06-03',
    endDate: '2023-06-07',
    routeCities: ['Полтава', 'Запоріжжя'],
    distance: 337,
  },
  {
    id: 4,
    customer: 'ТОВ "Еліт-Трейд"',
    carrier: 'ПП "ТрансЛогіст"',
    startLocation: 'Дніпро',
    endLocation: 'Київ',
    cargoWeight: 1200,
    maxWeight: 2200,
    carBrand: 'MAN',
    startDate: '2023-06-04',
    endDate: '2023-06-08',
    routeCities: ['Запоріжжя', 'Кропивницький', 'Черкаси'],
    distance: 379,
  },
  {
    id: 5,
    customer: 'ТОВ "Універсаль-Трейд"',
    carrier: 'ТОВ "УкрАвтоПрестиж"',
    startLocation: 'Одеса',
    endLocation: 'Львів',
    cargoWeight: 1800,
    maxWeight: 2800,
    carBrand: 'Iveco',
    startDate: '2023-06-05',
    endDate: '2023-06-09',
    routeCities: ['Миколаїв', 'Вінниця', 'Тернопіль'],
    distance: 773,
  },
  {
    id: 6,
    customer: 'ТОВ "Ділові Лінії"',
    carrier: 'ТОВ "АвтоТранс"',
    startLocation: 'Запоріжжя',
    endLocation: 'Дніпро',
    cargoWeight: 1500,
    maxWeight: 2500,
    carBrand: 'DAF',
    startDate: '2023-06-06',
    endDate: '2023-06-10',
    routeCities: ['Кропивницький', 'Полтава'],
    distance: 234,
  },
  {
    id: 7,
    customer: 'ФОП Сидоренко А.В.',
    carrier: 'ТОВ "Оптимальний Транспорт"',
    startLocation: 'Черкаси',
    endLocation: 'Одеса',
    cargoWeight: 1600,
    maxWeight: 2600,
    carBrand: 'Renault',
    startDate: '2023-06-07',
    endDate: '2023-06-11',
    routeCities: ['Київ', 'Вінниця', 'Миколаїв'],
    distance: 538,
  },
  {
    id: 8,
    customer: 'ТОВ "Міжнародний Експорт"',
    carrier: 'ТОВ "Українська Транспортна Компанія"',
    startLocation: 'Тернопіль',
    endLocation: 'Київ',
    cargoWeight: 1400,
    maxWeight: 2400,
    carBrand: 'Mercedes-Benz',
    startDate: '2023-06-08',
    endDate: '2023-06-12',
    routeCities: ['Львів', 'Вінниця', 'Черкаси'],
    distance: 444,
  },
  {
    id: 9,
    customer: 'ТОВ "Експорт-Імпорт"',
    carrier: 'ТОВ "Експрес Лайн"',
    startLocation: 'Миколаїв',
    endLocation: 'Харків',
    cargoWeight: 1900,
    maxWeight: 2900,
    carBrand: 'Volvo',
    startDate: '2023-06-09',
    endDate: '2023-06-13',
    routeCities: ['Одеса', 'Полтава'],
    distance: 581,
  },
  {
    id: 10,
    customer: 'ТОВ "Глобал Трейд"',
    carrier: 'ТОВ "УкрАвтоПрестиж"',
    startLocation: 'Вінниця',
    endLocation: 'Запоріжжя',
    cargoWeight: 1300,
    maxWeight: 2300,
    carBrand: 'Scania',
    startDate: '2023-06-10',
    endDate: '2023-06-14',
    routeCities: ['Київ', 'Кропивницький'],
    distance: 486,
  },
];
